//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiMoneyMate.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiMoneyMate.Translations.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string AdditionEntry_FontSize {
            get {
                return ResourceManager.GetString("AdditionEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string AdditionEntry_Placeholder {
            get {
                return ResourceManager.GetString("AdditionEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdditionEntry_Text {
            get {
                return ResourceManager.GetString("AdditionEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string AdditionTextLbl_FontSize {
            get {
                return ResourceManager.GetString("AdditionTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition:.
        /// </summary>
        internal static string AdditionTextLbl_Text {
            get {
                return ResourceManager.GetString("AdditionTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string AddNewLbl_FontSize {
            get {
                return ResourceManager.GetString("AddNewLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNewLbl_Text {
            get {
                return ResourceManager.GetString("AddNewLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of MauiMoneyMate already exists.
        /// </summary>
        internal static string AnInstanceOfMauiMoneyMateAlreadyExists {
            get {
                return ResourceManager.GetString("AnInstanceOfMauiMoneyMateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MauiMoneyMate.
        /// </summary>
        internal static string AppInfoMnuFlt_Text {
            get {
                return ResourceManager.GetString("AppInfoMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string ApplicationNameLbl_FontSize {
            get {
                return ResourceManager.GetString("ApplicationNameLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MauiMoneyMate.
        /// </summary>
        internal static string ApplicationNameLbl_Text {
            get {
                return ResourceManager.GetString("ApplicationNameLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        internal static string AppThemeMnuFlt_Text {
            get {
                return ResourceManager.GetString("AppThemeMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string BackMnuFlt_Text {
            get {
                return ResourceManager.GetString("BackMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string CancelBtn_FontSize {
            get {
                return ResourceManager.GetString("CancelBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtn_Text {
            get {
                return ResourceManager.GetString("CancelBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string CheckForUpdatesOnStartLbl_FontSize {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates at startup.
        /// </summary>
        internal static string CheckForUpdatesOnStartLbl_Text {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup finished successfully.
        /// </summary>
        internal static string CleanupFinishedSuccessfully {
            get {
                return ResourceManager.GetString("CleanupFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string ContinueWithoutSavingBtn_FontSize {
            get {
                return ResourceManager.GetString("ContinueWithoutSavingBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without saving.
        /// </summary>
        internal static string ContinueWithoutSavingBtn_Text {
            get {
                return ResourceManager.GetString("ContinueWithoutSavingBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string CopyrightLbl_FontSize {
            get {
                return ResourceManager.GetString("CopyrightLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2023 Tobias Schälte.
        /// </summary>
        internal static string CopyrightLbl_Text {
            get {
                return ResourceManager.GetString("CopyrightLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download update..
        /// </summary>
        internal static string CouldNotDownloadUpdate {
            get {
                return ResourceManager.GetString("CouldNotDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not install update.
        /// </summary>
        internal static string CouldNotInstallUpdate {
            get {
                return ResourceManager.GetString("CouldNotInstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be opened.
        /// </summary>
        internal static string CouldNotOpenFile {
            get {
                return ResourceManager.GetString("CouldNotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be saved.
        /// </summary>
        internal static string CouldNotSaveFile {
            get {
                return ResourceManager.GetString("CouldNotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditsLbl_FontSize {
            get {
                return ResourceManager.GetString("CreditsLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to {0} and {1} for their help with the color scheme and naming of the application..
        /// </summary>
        internal static string CreditsLbl_Text {
            get {
                return ResourceManager.GetString("CreditsLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DarkMnuFlt_Text {
            get {
                return ResourceManager.GetString("DarkMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string DeleteBtn_FontSize {
            get {
                return ResourceManager.GetString("DeleteBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtn_Text {
            get {
                return ResourceManager.GetString("DeleteBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string DeleteExpiredSalesBtn_FontSize {
            get {
                return ResourceManager.GetString("DeleteExpiredSalesBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sales expired at.
        /// </summary>
        internal static string DeleteExpiredSalesBtn_Text {
            get {
                return ResourceManager.GetString("DeleteExpiredSalesBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string DeleteTemporaryFilesBtn_FontSize {
            get {
                return ResourceManager.GetString("DeleteTemporaryFilesBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete temporary system files.
        /// </summary>
        internal static string DeleteTemporaryFilesBtn_Text {
            get {
                return ResourceManager.GetString("DeleteTemporaryFilesBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string DesignLbl_FontSize {
            get {
                return ResourceManager.GetString("DesignLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string DesignLbl_Text {
            get {
                return ResourceManager.GetString("DesignLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed view....
        /// </summary>
        internal static string DetailedSalesMnuFlt_Text {
            get {
                return ResourceManager.GetString("DetailedSalesMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed sales.
        /// </summary>
        internal static string DetailedSalesTitle {
            get {
                return ResourceManager.GetString("DetailedSalesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string DetailsBtn_FontSize {
            get {
                return ResourceManager.GetString("DetailsBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsBtn_Text {
            get {
                return ResourceManager.GetString("DetailsBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading newest version.
        /// </summary>
        internal static string DownloadingNewestVersion {
            get {
                return ResourceManager.GetString("DownloadingNewestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string DownloadUpdatesAutomaticallyLbl_FontSize {
            get {
                return ResourceManager.GetString("DownloadUpdatesAutomaticallyLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install updates automatically.
        /// </summary>
        internal static string DownloadUpdatesAutomaticallyLbl_Text {
            get {
                return ResourceManager.GetString("DownloadUpdatesAutomaticallyLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue closing the Application?.
        /// </summary>
        internal static string DoYouWantToContinueClosingTheApplication {
            get {
                return ResourceManager.GetString("DoYouWantToContinueClosingTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue opening another file?.
        /// </summary>
        internal static string DoYouWantToContinueOpeningAnotherFile {
            get {
                return ResourceManager.GetString("DoYouWantToContinueOpeningAnotherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string EditBtn_FontSize {
            get {
                return ResourceManager.GetString("EditBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditBtn_Text {
            get {
                return ResourceManager.GetString("EditBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditMnu_Text {
            get {
                return ResourceManager.GetString("EditMnu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string EndDateLbl_FontSize {
            get {
                return ResourceManager.GetString("EndDateLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string EndDateLbl_Text {
            get {
                return ResourceManager.GetString("EndDateLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string EndDateTextLbl_FontSize {
            get {
                return ResourceManager.GetString("EndDateTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string EndDateTextLbl_Text {
            get {
                return ResourceManager.GetString("EndDateTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting temporary files.
        /// </summary>
        internal static string ErrorWhileDeletingTemporaryFiles {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingTemporaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMnuFlt_Text {
            get {
                return ResourceManager.GetString("ExitMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string ExpensesCountLbl_FontSize {
            get {
                return ResourceManager.GetString("ExpensesCountLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thereof expenses:.
        /// </summary>
        internal static string ExpensesCountLbl_Text {
            get {
                return ResourceManager.GetString("ExpensesCountLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ExpensesTextLbl_FontSize {
            get {
                return ResourceManager.GetString("ExpensesTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string ExpensesTextLbl_Text {
            get {
                return ResourceManager.GetString("ExpensesTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ExportSettingsBtn_FontSize {
            get {
                return ResourceManager.GetString("ExportSettingsBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        internal static string ExportSettingsBtn_Text {
            get {
                return ResourceManager.GetString("ExportSettingsBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string FileHistoryDeleteBtn_FontSize {
            get {
                return ResourceManager.GetString("FileHistoryDeleteBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string FileHistoryDeleteBtn_Text {
            get {
                return ResourceManager.GetString("FileHistoryDeleteBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string FileHistoryOpenBtn_FontSize {
            get {
                return ResourceManager.GetString("FileHistoryOpenBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FileHistoryOpenBtn_Text {
            get {
                return ResourceManager.GetString("FileHistoryOpenBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMnu_Text {
            get {
                return ResourceManager.GetString("FileMnu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FilePageTitle {
            get {
                return ResourceManager.GetString("FilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string FinancialOverviewTitle {
            get {
                return ResourceManager.GetString("FinancialOverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to website....
        /// </summary>
        internal static string GoToWebsiteMnuFlt_Text {
            get {
                return ResourceManager.GetString("GoToWebsiteMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string HelpInfoLbl_FontSize {
            get {
                return ResourceManager.GetString("HelpInfoLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you notice a bug or problem, or simply have a suggestion for improvement, please create a new issue where your describe your problem. The title should start with &quot;MauiMoneyMate:&quot;..
        /// </summary>
        internal static string HelpInfoLbl_Text {
            get {
                return ResourceManager.GetString("HelpInfoLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMnu_Text {
            get {
                return ResourceManager.GetString("HelpMnu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string HelpTitleLbl_FontSize {
            get {
                return ResourceManager.GetString("HelpTitleLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MauiMoneyMate Help.
        /// </summary>
        internal static string HelpTitleLbl_Text {
            get {
                return ResourceManager.GetString("HelpTitleLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string HistoryLbl_FontSize {
            get {
                return ResourceManager.GetString("HistoryLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryLbl_Text {
            get {
                return ResourceManager.GetString("HistoryLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        /// </summary>
        internal static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import finished successfully.
        /// </summary>
        internal static string ImportFinishedSuccessfully {
            get {
                return ResourceManager.GetString("ImportFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ImportSettingsBtn_FontSize {
            get {
                return ResourceManager.GetString("ImportSettingsBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        internal static string ImportSettingsBtn_Text {
            get {
                return ResourceManager.GetString("ImportSettingsBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string IncomeCountLbl_FontSize {
            get {
                return ResourceManager.GetString("IncomeCountLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thereof income:.
        /// </summary>
        internal static string IncomeCountLbl_Text {
            get {
                return ResourceManager.GetString("IncomeCountLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string IncomeTextLbl_FontSize {
            get {
                return ResourceManager.GetString("IncomeTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string IncomeTextLbl_Text {
            get {
                return ResourceManager.GetString("IncomeTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete.
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing new version.
        /// </summary>
        internal static string InstallingNewVersion {
            get {
                return ResourceManager.GetString("InstallingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is no valid decimal..
        /// </summary>
        internal static string IsNoValidDecimal {
            get {
                return ResourceManager.GetString("IsNoValidDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is no valid integer.
        /// </summary>
        internal static string IsNoValidInteger {
            get {
                return ResourceManager.GetString("IsNoValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is no valid name.
        /// </summary>
        internal static string IsNoValidName {
            get {
                return ResourceManager.GetString("IsNoValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string IsOneTimeOrderLbl_FontSize {
            get {
                return ResourceManager.GetString("IsOneTimeOrderLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time order.
        /// </summary>
        internal static string IsOneTimeOrderLbl_Text {
            get {
                return ResourceManager.GetString("IsOneTimeOrderLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string LanguageLbl_FontSize {
            get {
                return ResourceManager.GetString("LanguageLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LanguageLbl_Text {
            get {
                return ResourceManager.GetString("LanguageLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LightThemeMnuFlt_Text {
            get {
                return ResourceManager.GetString("LightThemeMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} €.
        /// </summary>
        internal static string MoneyFormat {
            get {
                return ResourceManager.GetString("MoneyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string NameEntry_FontSize {
            get {
                return ResourceManager.GetString("NameEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameEntry_Placeholder {
            get {
                return ResourceManager.GetString("NameEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NameEntry_Text {
            get {
                return ResourceManager.GetString("NameEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string NameTextLbl_FontSize {
            get {
                return ResourceManager.GetString("NameTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameTextLbl_Text {
            get {
                return ResourceManager.GetString("NameTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New app version detected.
        /// </summary>
        internal static string NewAppVersionDetected {
            get {
                return ResourceManager.GetString("NewAppVersionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string NewIssueBtn_FontSize {
            get {
                return ResourceManager.GetString("NewIssueBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Issue.
        /// </summary>
        internal static string NewIssueBtn_Text {
            get {
                return ResourceManager.GetString("NewIssueBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewMnuFlt_Text {
            get {
                return ResourceManager.GetString("NewMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string NewSalesBtn_FontSize {
            get {
                return ResourceManager.GetString("NewSalesBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new sales.
        /// </summary>
        internal static string NewSalesBtn_Text {
            get {
                return ResourceManager.GetString("NewSalesBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string NewSaleTitleLbl_FontSize {
            get {
                return ResourceManager.GetString("NewSaleTitleLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new sales.
        /// </summary>
        internal static string NewSaleTitleLbl_Text {
            get {
                return ResourceManager.GetString("NewSaleTitleLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string OpenFileLbl_FontSize {
            get {
                return ResourceManager.GetString("OpenFileLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string OpenFileLbl_Text {
            get {
                return ResourceManager.GetString("OpenFileLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file....
        /// </summary>
        internal static string OpenFileMnuFlt_Text {
            get {
                return ResourceManager.GetString("OpenFileMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file page....
        /// </summary>
        internal static string OpenFilePageMnuFlt_Text {
            get {
                return ResourceManager.GetString("OpenFilePageMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenMnuFlt_Text {
            get {
                return ResourceManager.GetString("OpenMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently opened.
        /// </summary>
        internal static string OpenRecentMnuFlt_Text {
            get {
                return ResourceManager.GetString("OpenRecentMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings....
        /// </summary>
        internal static string OpenSettingsMnuFlt_Text {
            get {
                return ResourceManager.GetString("OpenSettingsMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview....
        /// </summary>
        internal static string OverviewMnuFlt_Text {
            get {
                return ResourceManager.GetString("OverviewMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again later..
        /// </summary>
        internal static string PleaseCheckYourInternetConnectionAndTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseCheckYourInternetConnectionAndTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string RedoMnuFlt_Text {
            get {
                return ResourceManager.GetString("RedoMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshMnuFlt_Text {
            get {
                return ResourceManager.GetString("RefreshMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string RepeatCycleMultiplierEntry_FontSize {
            get {
                return ResourceManager.GetString("RepeatCycleMultiplierEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string RepeatCycleMultiplierEntry_Placeholder {
            get {
                return ResourceManager.GetString("RepeatCycleMultiplierEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string RepeatCycleMultiplierEntry_Text {
            get {
                return ResourceManager.GetString("RepeatCycleMultiplierEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string RepeatCycleMultiplierTextLbl_FontSize {
            get {
                return ResourceManager.GetString("RepeatCycleMultiplierTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every:.
        /// </summary>
        internal static string RepeatCycleMultiplierTextLbl_Text {
            get {
                return ResourceManager.GetString("RepeatCycleMultiplierTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string RepeatCycleTextLbl_FontSize {
            get {
                return ResourceManager.GetString("RepeatCycleTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat cycle:.
        /// </summary>
        internal static string RepeatCycleTextLbl_Text {
            get {
                return ResourceManager.GetString("RepeatCycleTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program to apply the changes.
        /// </summary>
        internal static string RestartTheProgramToApplyTheChanges {
            get {
                return ResourceManager.GetString("RestartTheProgramToApplyTheChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string RestLbl_FontSize {
            get {
                return ResourceManager.GetString("RestLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest:.
        /// </summary>
        internal static string RestLbl_Text {
            get {
                return ResourceManager.GetString("RestLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string RestMoneyLbl_FontSize {
            get {
                return ResourceManager.GetString("RestMoneyLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string RestMoneyLbl_Text {
            get {
                return ResourceManager.GetString("RestMoneyLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string RightsReservedLbl_FontSize {
            get {
                return ResourceManager.GetString("RightsReservedLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string RightsReservedLbl_Text {
            get {
                return ResourceManager.GetString("RightsReservedLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SalesCountLbl_FontSize {
            get {
                return ResourceManager.GetString("SalesCountLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sales: .
        /// </summary>
        internal static string SalesCountLbl_Text {
            get {
                return ResourceManager.GetString("SalesCountLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string SalesEntry_FontSize {
            get {
                return ResourceManager.GetString("SalesEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,00.
        /// </summary>
        internal static string SalesEntry_Placeholder {
            get {
                return ResourceManager.GetString("SalesEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SalesEntry_Text {
            get {
                return ResourceManager.GetString("SalesEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string SalesLbl_FontSize {
            get {
                return ResourceManager.GetString("SalesLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string SalesLbl_Text {
            get {
                return ResourceManager.GetString("SalesLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string SaleTextLbl_FontSize {
            get {
                return ResourceManager.GetString("SaleTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale:.
        /// </summary>
        internal static string SaleTextLbl_Text {
            get {
                return ResourceManager.GetString("SaleTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string SaveAndContinueBtn_FontSize {
            get {
                return ResourceManager.GetString("SaveAndContinueBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; continue.
        /// </summary>
        internal static string SaveAndContinueBtn_Text {
            get {
                return ResourceManager.GetString("SaveAndContinueBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string SaveAsMnuFlt_Text {
            get {
                return ResourceManager.GetString("SaveAsMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string SaveBtn_FontSize {
            get {
                return ResourceManager.GetString("SaveBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtn_Text {
            get {
                return ResourceManager.GetString("SaveBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been saved: {0}.
        /// </summary>
        internal static string SavedFile {
            get {
                return ResourceManager.GetString("SavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string SaveFileAsLbl_FontSize {
            get {
                return ResourceManager.GetString("SaveFileAsLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File As.
        /// </summary>
        internal static string SaveFileAsLbl_Text {
            get {
                return ResourceManager.GetString("SaveFileAsLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string SaveFileLbl_FontSize {
            get {
                return ResourceManager.GetString("SaveFileLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string SaveFileLbl_Text {
            get {
                return ResourceManager.GetString("SaveFileLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveMnuFlt_Text {
            get {
                return ResourceManager.GetString("SaveMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string SavetBtn_FontSize {
            get {
                return ResourceManager.GetString("SavetBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string SearchForUpdateBtn_FontSize {
            get {
                return ResourceManager.GetString("SearchForUpdateBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for updates now.
        /// </summary>
        internal static string SearchForUpdateBtn_Text {
            get {
                return ResourceManager.GetString("SearchForUpdateBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMnu_Text {
            get {
                return ResourceManager.GetString("SettingsMnu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ShowFilePathInTitleBarLbl_FontSize {
            get {
                return ResourceManager.GetString("ShowFilePathInTitleBarLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file path in title bar.
        /// </summary>
        internal static string ShowFilePathInTitleBarLbl_Text {
            get {
                return ResourceManager.GetString("ShowFilePathInTitleBarLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string StartDateLbl_FontSize {
            get {
                return ResourceManager.GetString("StartDateLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string StartDateLbl_Text {
            get {
                return ResourceManager.GetString("StartDateLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string StartDateTextLbl_FontSize {
            get {
                return ResourceManager.GetString("StartDateTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string StartDateTextLbl_Text {
            get {
                return ResourceManager.GetString("StartDateTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string StartupLbl_FontSize {
            get {
                return ResourceManager.GetString("StartupLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string StartupLbl_Text {
            get {
                return ResourceManager.GetString("StartupLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string SystemLbl_FontSize {
            get {
                return ResourceManager.GetString("SystemLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemLbl_Text {
            get {
                return ResourceManager.GetString("SystemLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system theme.
        /// </summary>
        internal static string SystemThemeMnuFlt_Text {
            get {
                return ResourceManager.GetString("SystemThemeMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ThemeLbl_FontSize {
            get {
                return ResourceManager.GetString("ThemeLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme:.
        /// </summary>
        internal static string ThemeLbl_Text {
            get {
                return ResourceManager.GetString("ThemeLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can be no negative or non-existent number of repetitions..
        /// </summary>
        internal static string ThereCanBeNoNegaticeOrNonExistentNumberOfRepetitions {
            get {
                return ResourceManager.GetString("ThereCanBeNoNegaticeOrNonExistentNumberOfRepetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry already exists.
        /// </summary>
        internal static string ThisEntryAlreadyExists {
            get {
                return ResourceManager.GetString("ThisEntryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UndoMnuFlt_Text {
            get {
                return ResourceManager.GetString("UndoMnuFlt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string UnsavedChangesTextLbl_FontSize {
            get {
                return ResourceManager.GetString("UnsavedChangesTextLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes..
        /// </summary>
        internal static string UnsavedChangesTextLbl_Text {
            get {
                return ResourceManager.GetString("UnsavedChangesTextLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string UnsavedChangesTitle_FontSize {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        internal static string UnsavedChangesTitle_Text {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string UpdateBtn_FontSize {
            get {
                return ResourceManager.GetString("UpdateBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateBtn_Text {
            get {
                return ResourceManager.GetString("UpdateBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string UpdateInfoLbl_FontSize {
            get {
                return ResourceManager.GetString("UpdateInfoLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new app version was detected. Do you want to install it? The app needs to be restarted..
        /// </summary>
        internal static string UpdateInfoLbl_Text {
            get {
                return ResourceManager.GetString("UpdateInfoLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string UpdateTitleLbl_FontSize {
            get {
                return ResourceManager.GetString("UpdateTitleLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New app version detected.
        /// </summary>
        internal static string UpdateTitleLbl_Text {
            get {
                return ResourceManager.GetString("UpdateTitleLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update will be installed on closing the application.
        /// </summary>
        internal static string UpdateWillBeInstalledOnClosingTheApplication {
            get {
                return ResourceManager.GetString("UpdateWillBeInstalledOnClosingTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system language.
        /// </summary>
        internal static string UseSystemLanguage {
            get {
                return ResourceManager.GetString("UseSystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system theme.
        /// </summary>
        internal static string UseSystemTheme {
            get {
                return ResourceManager.GetString("UseSystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string VersionLbl_FontSize {
            get {
                return ResourceManager.GetString("VersionLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionLbl_Text {
            get {
                return ResourceManager.GetString("VersionLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMnu_Text {
            get {
                return ResourceManager.GetString("ViewMnu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a ticket....
        /// </summary>
        internal static string WriteTicketMnuFlt_Text {
            get {
                return ResourceManager.GetString("WriteTicketMnuFlt.Text", resourceCulture);
            }
        }
    }
}
