//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiMoneyMate.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiMoneyMate.Resources.Languages.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string AddNewLbl_FontSize {
            get {
                return ResourceManager.GetString("AddNewLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNewLbl_Text {
            get {
                return ResourceManager.GetString("AddNewLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string AllSalesLbl_FontSize {
            get {
                return ResourceManager.GetString("AllSalesLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllSalesLbl_Text {
            get {
                return ResourceManager.GetString("AllSalesLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already contains the entry {1}.
        /// </summary>
        internal static string AlreadyContainsEntry {
            get {
                return ResourceManager.GetString("AlreadyContainsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string CheckForUpdatesOnStartLbl_FontSize {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates at startup.
        /// </summary>
        internal static string CheckForUpdatesOnStartLbl_Text {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download update..
        /// </summary>
        internal static string CouldNotDownloadUpdate {
            get {
                return ResourceManager.GetString("CouldNotDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not install update.
        /// </summary>
        internal static string CouldNotInstallUpdate {
            get {
                return ResourceManager.GetString("CouldNotInstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be opened.
        /// </summary>
        internal static string CouldNotOpenFile {
            get {
                return ResourceManager.GetString("CouldNotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be saved.
        /// </summary>
        internal static string CouldNotSaveFile {
            get {
                return ResourceManager.GetString("CouldNotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string DeleteBtn_FontSize {
            get {
                return ResourceManager.GetString("DeleteBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtn_Text {
            get {
                return ResourceManager.GetString("DeleteBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string DesignLbl_FontSize {
            get {
                return ResourceManager.GetString("DesignLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string DesignLbl_Text {
            get {
                return ResourceManager.GetString("DesignLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading newest version.
        /// </summary>
        internal static string DownloadingNewestVersion {
            get {
                return ResourceManager.GetString("DownloadingNewestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string DownloadUpdatesAutomaticallyLbl_FontSize {
            get {
                return ResourceManager.GetString("DownloadUpdatesAutomaticallyLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install updates automatically.
        /// </summary>
        internal static string DownloadUpdatesAutomaticallyLbl_Text {
            get {
                return ResourceManager.GetString("DownloadUpdatesAutomaticallyLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string EditBtn_FontSize {
            get {
                return ResourceManager.GetString("EditBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditBtn_Text {
            get {
                return ResourceManager.GetString("EditBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string FileHistoryDeleteBtn_FontSize {
            get {
                return ResourceManager.GetString("FileHistoryDeleteBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string FileHistoryDeleteBtn_Text {
            get {
                return ResourceManager.GetString("FileHistoryDeleteBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string FileHistoryOpenBtn_FontSize {
            get {
                return ResourceManager.GetString("FileHistoryOpenBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FileHistoryOpenBtn_Text {
            get {
                return ResourceManager.GetString("FileHistoryOpenBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string FilePageBtn_FontSize {
            get {
                return ResourceManager.GetString("FilePageBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FilePageBtn_Text {
            get {
                return ResourceManager.GetString("FilePageBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FilePageTitle {
            get {
                return ResourceManager.GetString("FilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Overview.
        /// </summary>
        internal static string FinancialOverviewTitle {
            get {
                return ResourceManager.GetString("FinancialOverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string HelpBtn_FontSize {
            get {
                return ResourceManager.GetString("HelpBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpBtn_Text {
            get {
                return ResourceManager.GetString("HelpBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string HelpInfoLbl_FontSize {
            get {
                return ResourceManager.GetString("HelpInfoLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you notice a bug or problem, or simply have a suggestion for improvement, please create a new issue where your describe your problem. The title should start with &quot;MauiMoneyMate:&quot;..
        /// </summary>
        internal static string HelpInfoLbl_Text {
            get {
                return ResourceManager.GetString("HelpInfoLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string HelpTitleLbl_FontSize {
            get {
                return ResourceManager.GetString("HelpTitleLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MauiMoneyMate Help.
        /// </summary>
        internal static string HelpTitleLbl_Text {
            get {
                return ResourceManager.GetString("HelpTitleLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string HistoryLbl_FontSize {
            get {
                return ResourceManager.GetString("HistoryLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryLbl_Text {
            get {
                return ResourceManager.GetString("HistoryLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete.
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing new version.
        /// </summary>
        internal static string InstallingNewVersion {
            get {
                return ResourceManager.GetString("InstallingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no valid decimal..
        /// </summary>
        internal static string IsNoValidDecimal {
            get {
                return ResourceManager.GetString("IsNoValidDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string MoneyUnitLbl_FontSize {
            get {
                return ResourceManager.GetString("MoneyUnitLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        internal static string MoneyUnitLbl_Text {
            get {
                return ResourceManager.GetString("MoneyUnitLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string MonthlyAddBtn_FontSize {
            get {
                return ResourceManager.GetString("MonthlyAddBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MonthlyAddBtn_Text {
            get {
                return ResourceManager.GetString("MonthlyAddBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string MonthlyAdditionEntry_FontSize {
            get {
                return ResourceManager.GetString("MonthlyAdditionEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string MonthlyAdditionEntry_Placeholder {
            get {
                return ResourceManager.GetString("MonthlyAdditionEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MonthlyAdditionEntry_Text {
            get {
                return ResourceManager.GetString("MonthlyAdditionEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string MonthlyNameEntry_FontSize {
            get {
                return ResourceManager.GetString("MonthlyNameEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MonthlyNameEntry_Placeholder {
            get {
                return ResourceManager.GetString("MonthlyNameEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MonthlyNameEntry_Text {
            get {
                return ResourceManager.GetString("MonthlyNameEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string MonthlySalesEntry_FontSize {
            get {
                return ResourceManager.GetString("MonthlySalesEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,00.
        /// </summary>
        internal static string MonthlySalesEntry_Placeholder {
            get {
                return ResourceManager.GetString("MonthlySalesEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MonthlySalesEntry_Text {
            get {
                return ResourceManager.GetString("MonthlySalesEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string MonthlySalesLbl_FontSize {
            get {
                return ResourceManager.GetString("MonthlySalesLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string MonthlySalesLbl_Text {
            get {
                return ResourceManager.GetString("MonthlySalesLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New app version detected.
        /// </summary>
        internal static string NewAppVersionDetected {
            get {
                return ResourceManager.GetString("NewAppVersionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string NewIssueBtn_FontSize {
            get {
                return ResourceManager.GetString("NewIssueBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Issue.
        /// </summary>
        internal static string NewIssueBtn_Text {
            get {
                return ResourceManager.GetString("NewIssueBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string OpenFileLbl_FontSize {
            get {
                return ResourceManager.GetString("OpenFileLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string OpenFileLbl_Text {
            get {
                return ResourceManager.GetString("OpenFileLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again later..
        /// </summary>
        internal static string PleaseCheckYourInternetConnectionAndTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseCheckYourInternetConnectionAndTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string RestLbl_FontSize {
            get {
                return ResourceManager.GetString("RestLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest:.
        /// </summary>
        internal static string RestLbl_Text {
            get {
                return ResourceManager.GetString("RestLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string RestMoneyLbl_FontSize {
            get {
                return ResourceManager.GetString("RestMoneyLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string RestMoneyLbl_Text {
            get {
                return ResourceManager.GetString("RestMoneyLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been saved: {0}.
        /// </summary>
        internal static string SavedFile {
            get {
                return ResourceManager.GetString("SavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string SaveFileAsLbl_FontSize {
            get {
                return ResourceManager.GetString("SaveFileAsLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File As.
        /// </summary>
        internal static string SaveFileAsLbl_Text {
            get {
                return ResourceManager.GetString("SaveFileAsLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string SaveFileLbl_FontSize {
            get {
                return ResourceManager.GetString("SaveFileLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string SaveFileLbl_Text {
            get {
                return ResourceManager.GetString("SaveFileLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string SearchForUpdateBtn_FontSize {
            get {
                return ResourceManager.GetString("SearchForUpdateBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for updates now.
        /// </summary>
        internal static string SearchForUpdateBtn_Text {
            get {
                return ResourceManager.GetString("SearchForUpdateBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string SettingsPageBtn_FontSize {
            get {
                return ResourceManager.GetString("SettingsPageBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageBtn_Text {
            get {
                return ResourceManager.GetString("SettingsPageBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ShowFilePathInTitleBarLbl_FontSize {
            get {
                return ResourceManager.GetString("ShowFilePathInTitleBarLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file path in title bar.
        /// </summary>
        internal static string ShowFilePathInTitleBarLbl_Text {
            get {
                return ResourceManager.GetString("ShowFilePathInTitleBarLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string StartupLbl_FontSize {
            get {
                return ResourceManager.GetString("StartupLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string StartupLbl_Text {
            get {
                return ResourceManager.GetString("StartupLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string UpdateBtn_FontSize {
            get {
                return ResourceManager.GetString("UpdateBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateBtn_Text {
            get {
                return ResourceManager.GetString("UpdateBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string UpdateInfoLbl_FontSize {
            get {
                return ResourceManager.GetString("UpdateInfoLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new app version was detected. Do you want to install it? The app needs to be restarted..
        /// </summary>
        internal static string UpdateInfoLbl_Text {
            get {
                return ResourceManager.GetString("UpdateInfoLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string UpdateTitleLbl_FontSize {
            get {
                return ResourceManager.GetString("UpdateTitleLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New app version detected.
        /// </summary>
        internal static string UpdateTitleLbl_Text {
            get {
                return ResourceManager.GetString("UpdateTitleLbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update will be installed on closing the application.
        /// </summary>
        internal static string UpdateWillBeInstalledOnClosingTheApplication {
            get {
                return ResourceManager.GetString("UpdateWillBeInstalledOnClosingTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string YearlyAddBtn_FontSize {
            get {
                return ResourceManager.GetString("YearlyAddBtn.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string YearlyAddBtn_Text {
            get {
                return ResourceManager.GetString("YearlyAddBtn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string YearlyAdditionEntry_FontSize {
            get {
                return ResourceManager.GetString("YearlyAdditionEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string YearlyAdditionEntry_Placeholder {
            get {
                return ResourceManager.GetString("YearlyAdditionEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string YearlyAdditionEntry_Text {
            get {
                return ResourceManager.GetString("YearlyAdditionEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string YearlyNameEntry_FontSize {
            get {
                return ResourceManager.GetString("YearlyNameEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string YearlyNameEntry_Placeholder {
            get {
                return ResourceManager.GetString("YearlyNameEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string YearlyNameEntry_Text {
            get {
                return ResourceManager.GetString("YearlyNameEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string YearlySalesEntry_FontSize {
            get {
                return ResourceManager.GetString("YearlySalesEntry.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,00.
        /// </summary>
        internal static string YearlySalesEntry_Placeholder {
            get {
                return ResourceManager.GetString("YearlySalesEntry.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string YearlySalesEntry_Text {
            get {
                return ResourceManager.GetString("YearlySalesEntry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string YearlySalesLbl_FontSize {
            get {
                return ResourceManager.GetString("YearlySalesLbl.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string YearlySalesLbl_Text {
            get {
                return ResourceManager.GetString("YearlySalesLbl.Text", resourceCulture);
            }
        }
    }
}
